[build-system]
requires = [
    "setuptools",
    "wheel",
    "scikit-build>=0.14.1",
    "ninja; platform_system!='Windows'",
    "cmake>=3.16",
    "oldest-supported-numpy",
    "pybind11>=2.8.1",
]
build-backend = "setuptools.build_meta"
