"""Project: ModelMetricUncertainty

Created: 2021/09/24

Description:
    setup script to install ModelMetricUncertainty package.

Authors:
    Ralph Urlus [rurlus.dev@gmail.com]

Redistribution and use in source and binary forms, with or without
modification, are permitted according to the terms listed in the file
LICENSE.
"""

import re
import os
import sys
import glob
import shutil
import subprocess
from pathlib import Path
from warnings import warn
from setuptools import find_packages
from setuptools import setup, Extension
from setuptools.command.build_ext import build_ext
from distutils.errors import CompileError, DistutilsExecError, DistutilsPlatformError

NAME = 'mmu'

MAJOR = 0
REVISION = 0
PATCH = 0
DEV = True

# note: also update README.rst

VERSION = '{major}.{revision}.{patch}'.format(major=MAJOR, revision=REVISION, patch=PATCH)
FULL_VERSION = VERSION
if DEV:
    FULL_VERSION += '.dev'

TEST_REQUIREMENTS = ['pytest>=4.0.2',]

REQUIREMENTS = [
    'numpy>=1.18.0',
    'scipy>=1.5.2',
    'pandas>=0.25.1',
    'matplotlib>=2.2.3',
]

EXTRA_REQUIREMENTS = {
    'test': TEST_REQUIREMENTS,
}

if DEV:
    REQUIREMENTS += TEST_REQUIREMENTS

EXCLUDE_PACKAGES = []

# read the contents of readme file
with open("README.md", encoding="utf-8") as f:
    long_description = f.read()

def write_version_py(filename: str = 'mmu/version.py') -> None:
    """Write package version to version.py.

    This will ensure that the version in version.py is in sync with us.

    Parameters
    ----------
    filename : str
        the path the file to write the version.py

    """
    # Do not modify the indentation of version_str!
    version_str = """\"\"\"THIS FILE IS AUTO-GENERATED BY ModelMetricUncertainty SETUP.PY.\"\"\"

name = '{name!s}'
version = '{version!s}'
full_version = '{full_version!s}'
release = {is_release!s}
"""

    with open(filename, 'w') as version_file:
        version_file.write(
            version_str.format(name=NAME.lower(), version=VERSION, full_version=FULL_VERSION, is_release=not DEV)
        )


setup_args = {
    'name': NAME,
    'version': FULL_VERSION,
    'url': 'https://github.com/RUrlus/ModelMetricUncertainty',
    'license': 'Apache-2',
    'author': 'Ralph Urlus',
    'author_email': 'rurlus.dev@gmail.com',
    'description': "ModelMetricUncertainty library",
    'long_description': long_description,
    'long_description_content_type': "text/x-rst",
    'python_requires': '>=3.7',
    'packages': find_packages(exclude=EXCLUDE_PACKAGES),
    # Setuptools requires that package data are located inside the package.
    # This is a feature and not a bug, see
    # http://setuptools.readthedocs.io/en/latest/setuptools.html#non-package-data-files
    'package_data': {NAME.lower(): []},
    'include_package_data': True,
    'install_requires': REQUIREMENTS,
    'extras_require': EXTRA_REQUIREMENTS,
    'tests_require': TEST_REQUIREMENTS,
    'zip_safe': False,
    'classifiers': [
        "Programming Language :: Python :: 3",
        "Operating System :: OS Independent",
        "License :: OSI Approved :: Apache Software License",
    ],
}

if __name__ == '__main__':
    write_version_py()
    setup(**setup_args)
