name: Asan

on:
  pull_request:
    branches:
      - stable
      - unstable
  workflow_dispatch:

defaults:
  run:
    shell: bash

jobs:
  pre_job:
    # continue-on-error: true # Uncomment once integration is finished
    runs-on: ubuntu-latest
    # Map a step output to a job output
    outputs:
      should_skip: ${{ steps.skip_check.outputs.should_skip }}
    steps:
      - id: skip_check
        uses: fkirc/skip-duplicate-actions@master
        with:
          # All of these options are optional, so you can remove them if you are happy with the defaults
          cancel_others: 'true'
          do_not_skip: '["pull_request", "workflow_dispatch", "schedule"]'
  build:
    name: Asan
    needs: pre_job
    if: ${{ needs.pre_job.outputs.should_skip != 'true' }}
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
        with:
          submodules: false

      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install python packages
        run: |
          python -m pip install --upgrade pip setuptools wheel
          python -m pip install --upgrade pybind11 cmake ninja pytest

      - name: Install packages
        run: |
          CMAKE_ARGS="-DMMU_ENABLE_INTERNAL_TESTS=ON -DMMU_DISABLE_OPENMP=ON -DMMU_ENABLE_ARCH_FLAGS=OFF -DCMAKE_BUILD_TYPE=Debug" python -m pip install . -v

      - name: Test
        run: |
          cd tests
          LD_PRELOAD=$(clang -print-file-name=libclang_rt.asan-x86_64.so) \
          ASAN_OPTIONS=detect_leaks=0 \
          PYTHONMALLOC=malloc \
          python -m pytest
