name: Build and Test Matrix

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
      - unstable
  push:
    branches:
      - main
      - unstable

defaults:
  run:
    shell: bash

jobs:
  pre_job:
    # continue-on-error: true # Uncomment once integration is finished
    runs-on: ubuntu-latest
    # Map a step output to a job output
    outputs:
      should_skip: ${{ steps.skip_check.outputs.should_skip }}
    steps:
      - id: skip_check
        uses: fkirc/skip-duplicate-actions@master
        with:
          # All of these options are optional, so you can remove them if you are happy with the defaults
          cancel_others: 'true'
          do_not_skip: '["pull_request", "workflow_dispatch"]'
  build:
    name: ${{ matrix.config.name }}
    needs: pre_job
    if: ${{ needs.pre_job.outputs.should_skip != 'true' }}
    runs-on: ${{ matrix.config.os }}
    strategy:
      fail-fast: false
      matrix:
        config: 
        - {
            name: "Windows (MSVC)",
            os: windows-latest,
            build_type: "Release",
            cc: "cl",
            cxx: "cl",
            environment_script: "C:/Program Files (x86)/Microsoft Visual Studio/2019/Enterprise/VC/Auxiliary/Build/vcvars64.bat",
            generators: "Visual Studio 16 2019",
            target: "ALL_BUILD"
          }
        - {
            name: "Ubuntu (Clang-10)",
            os: ubuntu-latest,
            build_type: "Release",
            cc: "clang-10",
            cxx: "clang++-10",
            generators: "Ninja",
            target: "all"
          }
        - {
            name: "Ubuntu (GCC-9)",
            os: ubuntu-latest,
            build_type: "Release",
            cc: "gcc-9",
            cxx: "g++-9",
            generators: "Ninja",
            target: "all"
          }
        - {
            name: "macOS (Clang)",
            os: macos-latest,
            build_type: "Release",
            cc: "clang",
            cxx: "clang++",
            generators: "Ninja",
            target: "all"
          }

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
        with:
          submodules: true

      - uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - uses: seanmiddleditch/gha-setup-ninja@master

      - name: Print env
        run: |
          echo github.event.action: ${{ github.event.action }}
          echo github.event_name: ${{ github.event_name }}

      - name: Install dependencies on windows
        if: startsWith(matrix.config.os, 'windows')
        run: |
          choco install cmake
          ninja --version
          cmake --version

      - name: Install dependencies on ubuntu
        if: runner.os == 'Linux'
        run: |
          python -m pip install --upgrade cmake
          ninja --version
          cmake --version

      - name: Install dependencies on macos
        if: startsWith(matrix.config.os, 'macos')
        run: |
          python -m pip install cmake
          ninja --version
          cmake --version
      
      - name: Install python pacakges
        run: |
          python -m pip install --upgrade pip setuptools wheel
          python -m pip install numpy pybind11
          
      - name: Configure
        run: |
          cmake -G "${{ matrix.config.generators }}"\
            -S . -B build \
            -DCMAKE_BUILD_TYPE=${{ matrix.config.build_type }} \
           -Dpybind11_DIR=$(python3 -c 'import pybind11; print(pybind11.get_cmake_dir())') \
           -DPython3_EXECUTABLE=$(python3 -c 'import sys; print(sys.executable)')

      - name: Build
        run: |
            cmake \
              --build build \
              --target ${{ matrix.config.target }} \
              --config ${{ matrix.config.build_type }}

      - name: Test
        run: python3 -c 'import build.cpp._mmu_core as c; print(c.confusion_matrix)'
