name: Linux

defaults:
  run:
    shell: bash

on:
  workflow_dispatch:
  pull_request:
    branches:
      - stable
      - unstable
  push:
    branches:
      - stable
  schedule:
    - cron: '0 23 * * 1'

jobs:
  pre_job:
    # continue-on-error: true # Uncomment once integration is finished
    runs-on: ubuntu-latest
    # Map a step output to a job output
    outputs:
      should_skip: ${{ steps.skip_check.outputs.should_skip }}
    steps:
      - id: skip_check
        uses: fkirc/skip-duplicate-actions@master
        with:
          # All of these options are optional, so you can remove them if you are happy with the defaults
          cancel_others: 'true'
          do_not_skip: '["pull_request", "workflow_dispatch", "schedule"]'
  tests:
    runs-on: ${{ matrix.config.os }}
    name: ${{ matrix.config.name }} Python ${{ matrix.python-version }}
    needs: pre_job
    if: ${{ needs.pre_job.outputs.should_skip != 'true' }}
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.7", "3.8", "3.9", "3.10"]
        config: 
        - {
            name: "Ubuntu (Clang-11)",
            os: ubuntu-latest,
            build_type: "Release",
            cc: "clang-11",
            cxx: "clang++-11",
            generators: "Ninja",
            target: "all"
          }
        - {
            name: "Ubuntu (GCC-10)",
            os: ubuntu-latest,
            build_type: "Release",
            cc: "gcc-10",
            cxx: "g++-10",
            generators: "Ninja",
            target: "all"
          }
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: true

    - uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}

    - name: Add requirements
      run: python -m pip install --upgrade pip wheel setuptools pytest

    - name: Build and install
      run: CXX=${{ matrix.config.cxx }} CMAKE_ARGS="-DMMU_ENABLE_INTERNAL_TESTS=ON -DMMU_CICD_MODE=ON" pip install --verbose .

    - name: Unit test
      run: pytest tests
