name: MacOS

defaults:
  run:
    shell: bash

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
      - unstable
  push:
    branches:
      - main
      - unstable

jobs:
  pre_job:
    # continue-on-error: true # Uncomment once integration is finished
    runs-on: ubuntu-latest
    # Map a step output to a job output
    outputs:
      should_skip: ${{ steps.skip_check.outputs.should_skip }}
    steps:
      - id: skip_check
        uses: fkirc/skip-duplicate-actions@master
        with:
          # All of these options are optional, so you can remove them if you are happy with the defaults
          cancel_others: 'true'
          do_not_skip: '["pull_request", "workflow_dispatch", "schedule"]'
  tests:
    runs-on: ${{ matrix.config.os }}
    name: ${{ matrix.config.name }} Python ${{ matrix.python-version }}
    needs: pre_job
    if: ${{ needs.pre_job.outputs.should_skip != 'true' }}
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.7", "3.8", "3.9"]
        config: 
        - {
            name: "macOS (Clang)",
            os: macos-latest,
            build_type: "Release",
            cc: "clang",
            cxx: "clang++",
            generators: "Ninja",
            target: "all"
          }
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true

    - uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Add requirements
      run: python -m pip install --upgrade pip wheel setuptools

    - name: Build and install
      run: CXX=${{ matrix.config.cxx }} MMU_BUILD_TESTS=on pip install --verbose .

    - name: Install test dependencies
      run: pip install pytest

    - name: Unit test
      run: pytest tests
